#!/bin/bash
#
# Copyright Tim Keitt
# Licensed under the GPL (http://www.gnu.org/)
#
# Usage: install_packages [package-names]
#
# If any of package-names names a file containing package names,
# these will be read and installed as well
#
INSTALL_LIST=$@
PACKAGE_LIST=""

for PACKAGE in $INSTALL_LIST
do
	if [ -r $PACKAGE ]
	then
		FTYPE=$(file -b $PACKAGE | cut -f 1 -d " ")
		if [ "$FTYPE" = "ASCII" ]
		then
			PACKAGE_LIST="${PACKAGE_LIST} $(cat $PACKAGE)"
		fi
	else
		PACKAGE_LIST="${PACKAGE_LIST} $PACKAGE"
	fi
done

PROGNAME=`basename ${0}`
LOG_FILE=${PROGNAME}.log

REINSTALL_ALL=n
echo -n "Enter y to reinstall all packages: "
read REINSTALL_ALL

UPDATE_ALL=n
if [ "$REINSTALL_ALL" != "y" ]
then
	echo -n "Enter y update all packages: "
	read UPDATE_ALL
fi

echo -n "Enter y to send email when finished: "
read SEND_EMAIL

echo
echo "Going to background..."
echo

( # Start subshell

exec > $LOG_FILE 2>&1

R --vanilla << EOF
options(repos = "http://www.revolution-computing.com/cran")
instpkgs = installed.packages()[,1]
if ( identical("${REINSTALL_ALL}", "y") ) install.packages(instpkgs)
if ( identical("${UPDATE_ALL}", "y") ) update.packages(ask = FALSE)
pkglist = strsplit("${PACKAGE_LIST}", " ")
for ( pkg in pkglist )
{
	if ( !identical(pkg, "") ) install.packages(pkg)
}

cat("Done\n")
EOF

if [ "$SEND_EMAIL" = "y" ]
then
mail -s "$PROGNAME completed" $USER << EOF
$PROGNAME completed on `hostname`
EOF
fi

) & # End subshell

exit

